package com.example.demo.entity;


import jakarta.persistence.*;
//Mapping Class Name to database table name
@Entity(name="todo")
public class Todo {
    //id is primary key and autogenerated by table
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name="id")
    private int id;

    @Column(name="entry")
    private String entry;

    @Column(name="severity")
    private String severity;

    @Column(name="done")
    private boolean done;
    @Column(name="name")
    private String name;

    //Defining constructors

    public Todo() {
    }

    public Todo(String entry) {
        this.entry = entry;
    }


    //Defining getters and setters

    public int getId() {
        return id;
    }


    public String getEntry() {
        return entry;
    }

    public void setEntry(String entry) {
        this.entry = entry;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public boolean isDone() {
        return done;
    }

    public void setDone(boolean done) {
        this.done = done;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    //toString() method


    @Override
    public String toString() {
        return "Todo{" +
                "id=" + id +
                ", entry='" + entry + '\'' +
                ", severity='" + severity + '\'' +
                ", done=" + done +
                ", name='" + name + '\'' +
                '}';
    }
}
